### ISSUE TITLE
Confetti - need to support feed results accepted and step id

### ISSUE THREAD

**Issue by psysoo** [GuideBlocks-org/iOS-GuideBlocks#50]
Confetti - need to support feed results accepted and step id
Currently only sends feedACK (view counts in guide analytic)
<img width="964" alt="Screenshot 2024-02-29 at 11 17 25 am" src="https://github.com/GuideBlocks-org/iOS-GuideBlocks/assets/114545794/0423a039-dac9-4eb7-926a-3dd58fda1d81">

**Comment by amraboelela** [comment]
This only comes for couple seconds and goes away, don't think the user can accept or reject the Confetti GB.

**Comment by psysoo** [comment]
please ensure there is nextStepOfGuide method (https://docs.contextu.al/sdks/ios/reference/guideblocks/ctxbaseguidecontroller/overview/) and should call it when Conffeti completed

**Comment by amraboelela** [comment]
Check after merging #76 
<img width="990" alt="Screenshot 2024-03-05 at 7 31 09 PM" src="https://github.com/GuideBlocks-org/iOS-GuideBlocks/assets/882954/dba6bf86-989f-4320-989b-46a9078d2acc">

**Comment by psysoo** [comment]
test passed against App Version:2.3+1709259341
