### ISSUE TITLE
OpenChecklist - It needs to use SurveyTemplate

### ISSUE THREAD

**Issue by psysoo** [GuideBlocks-org/iOS-GuideBlocks#59]
https://github.com/GuideBlocks-org/iOS-GuideBlocks/blob/develop/Sources/GuideBlocks/OpenChecklist/README.md

Please fix #6 pick one of the “Standard” Contextual Announcement Templates 
->  pick one of the “Standard” Contextual Survey Templates

#6 Preview the Announcement on your Phone - it should look similar to the template
->  Preview the Survey on your Phone 
(it doesn't look similar to the template at all, please add the pic for its first look / https://github.com/GuideBlocks-org/iOS-GuideBlocks/blob/develop/Sources/GuideBlocks/OpenChecklist/openchecklist-guideblock.png is the second look after clicking the guide button)

#8 If you are still in Preview Mode, then you should see the Announcement will magically change to OpenChecklist.
-> If you are still in Preview Mode, then you should see the Survey will magically change to OpenChecklist.

**Comment by amraboelela** [comment]
@mdstroebel and @psysoo why does it need to you Survey and not Announcement Template? Both of them don't exactly match what we are doing here anyway :)

**Comment by djinoz** [comment]
I think the logic was that checklist could fit the feedback UI in the dash but you are correct that the checklist requires other Json elements that the feedback dropdown doesn't have, so we Ieave it in extra_json.

Closing.
