### ISSUE TITLE
QRCode - cannot edit the guide size 

### ISSUE THREAD

**Issue by psysoo** [GuideBlocks-org/iOS-GuideBlocks#63]
QRCode - cannot edit the blue guide size by the container size that is set on dashboard 
if it's editable by extra_json, please add it in .yml

<img width="406" alt="Screenshot 2024-03-01 at 10 39 14 am" src="https://github.com/GuideBlocks-org/iOS-GuideBlocks/assets/114545794/4fd6547f-8053-46e5-a07b-5d5745805c48">

**Comment by amraboelela** [comment]
@mdstroebel I only see guide.title and guide.content as shown in this code snippet, but not guide.container, any idea?

`let guide = contextualContainer.guidePayload.guide
        var view = QRButtonView(
            imageElement: guide.arrayImages.first,
            viewModel: qrViewModel,
            closeButtonTapped: {
                self.dismissGuide()
                self.closeButtonTapped?()
            }
        )
        view.titleTextElement = guide.title
        view.contentTextElement = guide.content`

**Comment by mdstroebel** [comment]
@amraboelela If you want to see the `container` values that come from the Dashboard, they are in the root of that `guide` object.

```
let guide = contextualContainer.guidePayload.guide
let containerWidth = guide.width
let containerHeight = guide.height
let borderColor = guide.borderColor
let backgroundColor = guide.backgroundColor
// etc

// NOTE: there is also `widthUnit` and `heightUnit` - these are old and were added to provide compatibility for both `px` and `%` when entered in the Dashboard
```

**Comment by amraboelela** [comment]
@mdstroebel Thanks Marc, yes I figured that out, and I was suggesting to change the var name from `guidePayload.guide` to `guidePayload.container` to make things more clear.

**Comment by mdstroebel** [comment]
aaah I see, honestly I would rather move the actual object to within the `guide` object so that it represents what you see on the Dashboard more clearly.

e.g.
```
let guide = contextualContainer.guide
let container = guide.container
let title = guide.title
let content = guide.content
```

But any changes to this would need to come later obviously 👍

**Comment by amraboelela** [comment]
yes I was expecting it to be like that :), that's why I thought the container is missing

**Comment by amraboelela** [comment]
Please check, after merging:
https://github.com/GuideBlocks-org/iOS-GuideBlocks/pull/66

<img width="729" alt="Screenshot 2024-03-01 at 5 42 35 PM" src="https://github.com/GuideBlocks-org/iOS-GuideBlocks/assets/882954/1b5591d5-f1f1-4ad4-965d-e37dd86d84fc">

**Comment by djinoz** [comment]
Merged

**Comment by amraboelela** [comment]
Ok try after merging #71

**Comment by psysoo** [comment]
test passed on develop branch [509ff81](https://github.com/GuideBlocks-org/iOS-GuideBlocks/commit/509ff81ff4af50b34e2fddb2af6a7028a4b9594b)
