### ISSUE TITLE
QRCode - support navigate the site 

### ISSUE THREAD

**Issue by psysoo** [GuideBlocks-org/iOS-GuideBlocks#64]
QRCode - support navigate the site in QR 
Where the QRCode should allow users to navigate to a website, but instead, it only displays the text included in the QRCode.

<img width="462" alt="Screenshot 2024-03-01 at 10 38 20 am" src="https://github.com/GuideBlocks-org/iOS-GuideBlocks/assets/114545794/5dea9b84-c8d0-4e82-a6d4-9a82c27999f3">

**Comment by djinoz** [comment]
Disagree on this, the QR code does not have to be a URL it can be any string and the app can use it anyway it likes. 
Also if it is a URL, I would still keep this guideblock single purpose.

**Comment by psysoo** [comment]
@djinoz 
As a user, I primarily use QR codes for navigation. Whether for accessing information or performing actions, it's helpful if the QR code content is easily copyable or clickable.

**Comment by djinoz** [comment]
Thanks @psysoo  Noted.
The initial requirement was to scan and get an app_key, so I won't block release for this. However, I will review for future.
