### ISSUE TITLE
FancyAnnouncement - Invalid redeclaration of 'contextualContainer'

### ISSUE THREAD

**Issue by psysoo** [GuideBlocks-org/iOS-GuideBlocks#81]
@amraboelela  please review this issue. 
I got airbnb sample build failed from this Invalid redeclaration of 'contextualContainer'
<img width="983" alt="Screenshot 2024-03-07 at 4 07 10 pm" src="https://github.com/GuideBlocks-org/iOS-GuideBlocks/assets/114545794/0acec75d-6def-4511-a433-1f1a5c995a4a">

**Comment by amraboelela** [comment]
Hi @psysoo pls get the latest code from develop, as I don't see this error here:

<img width="800" alt="Screenshot 2024-03-07 at 9 22 26 AM" src="https://github.com/GuideBlocks-org/iOS-GuideBlocks/assets/882954/ea741cfd-7f24-4095-ae1c-5200e27cf2e6">

**Comment by psysoo** [comment]
@amraboelela  hmm, I still can see the invalid code in 
https://github.com/GuideBlocks-org/iOS-GuideBlocks/blob/develop/Sources/GuideBlocks/FancyAnnouncement/FancyAnnouncementGuideController.swift

**Comment by amraboelela** [comment]
@mdstroebel Fixed it
<img width="1248" alt="Screenshot 2024-03-07 at 9 12 03 PM" src="https://github.com/GuideBlocks-org/iOS-GuideBlocks/assets/882954/8448b3b6-0ae9-46b6-833d-dcf177e46839">
